language: node_js

node_js:
   - "12.13.1"

before_script: # commands to run before the build step
   - npm install -g --silent @angular/cli

cache:
  directories:
    - "node_modules"

script: # the build step
   - ng build --prod